# ----------------------------------------------------------------------------
#
# Package             : Pillow
# Source Repo         : https://github.com/python-pillow/Pillow
# Travis Job Link     : https://travis-ci.com/github/asellappen/Pillow/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------


language: python
sudo: false

dist: bionic
matrix:
    include:
        - python: 3.8
          env: TOXENV=py38
          sudo: true
          arch : ppc64le
before_install:
        - pip install hypothesis
        - pip install codecov
        - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
             pip install PIL;
             pip install image;
             echo "Running before install  ppc64le";
          else
             echo "skipped  before install  amd64";
          fi
install:
        - travis_retry pip install tox
script:
        - .ci/build.sh
        - .ci/install.sh
        - .ci/test.sh
        - travis_retry tox
        - coverage run conftest.py
